/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -l DeviceInstance -a DeviceInstance_dbusif org.lirid.receiver.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DeviceInstance_dbusif.h"
#include "DeviceInstance.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceAdaptor
 */

DeviceAdaptor::DeviceAdaptor(DeviceInstance *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceAdaptor::~DeviceAdaptor()
{
    // destructor
}

DeviceInstance* DeviceAdaptor::parent() const
{
	return static_cast<DeviceInstance *>(QObject::parent());
}

int DeviceAdaptor::ReceiverState()
{
    // handle method call org.liri.Device.ReceiverState
    return parent()->ReceiverState();
}

QMap<QString,QString> DeviceAdaptor::getAllSettings()
{
    // handle method call org.liri.Device.getAllSettings
    return parent()->getAllSettings();
}

QStringList DeviceAdaptor::getSettings(const QStringList &keys)
{
    // handle method call org.liri.Device.getSettings
    return parent()->getSettings(keys);
}

void DeviceAdaptor::setSettings(const QMap<QString,QString> &settings)
{
    // handle method call org.liri.Device.setSettings
    parent()->setSettings(settings);
}

